version: '3'
services:
  api:
    image: go_api
    ports:
      - "4000:3030"
    depends_on:
      - db
    networks:
      - backend_stack
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/data/db"
    networks:
      - backend_stack
volumes:
  mongodata:
networks:
  backend_stack:
    driver: overlay